# Generated by Django 3.2.9 on 2022-03-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default='http://www.youtube.com/embed/cxB4ACaaR4I'),
        ),
    ]
