# Generated by Django 3.2.9 on 2022-01-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Snacks'), ('E', 'Entre'), ('D', 'Drink'), ('A', 'Appetizer'), ('MC', 'Main Course')], max_length=3),
        ),
    ]
