# Generated by Django 3.2.9 on 2022-01-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
