# Generated by Django 3.2.9 on 2021-12-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_auto_20211222_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description'),
            preserve_default=False,
        ),
    ]
