# Generated by Django 3.2.9 on 2021-12-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0014_auto_20211228_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
