# Generated by Django 3.2.9 on 2021-12-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0015_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
