# Generated by Django 3.2.9 on 2021-12-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0018_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
